# Generated by Django 4.1 on 2022-08-19 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='img_uri_female',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='img_uri_male',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='verif_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_institution', models.CharField(blank=True, max_length=200, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('university_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('linked_in', models.CharField(blank=True, max_length=200, null=True)),
                ('academia_publication', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_1', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_2', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_3', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_4', models.CharField(blank=True, max_length=200, null=True)),
                ('publication_5', models.CharField(blank=True, max_length=200, null=True)),
                ('permission_to_display_contact_information', models.BooleanField(default=False)),
                ('permission_to_display_publications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
