# Generated by Django 4.1 on 2022-08-19 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_species_img_uri_female_species_img_uri_male_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='user',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
