# Generated by Django 4.1 on 2022-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_species_img_uri_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='clutch_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='clutch_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
