# Generated by Django 4.1 on 2022-09-05 18:23

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_species_clutch_max_alter_species_clutch_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='size_max_male',
            field=models.FloatField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
    ]
