# Generated by Django 4.1 on 2022-09-05 18:45

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_species_size_max_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='clutch_avg',
            field=models.FloatField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='species',
            name='clutch_max',
            field=models.IntegerField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='species',
            name='clutch_min',
            field=models.IntegerField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='species',
            name='egg_diameter',
            field=models.FloatField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='species',
            name='longevity',
            field=models.FloatField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='species',
            name='range_size',
            field=models.FloatField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='species',
            name='size_max_female',
            field=models.FloatField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
        migrations.AlterField(
            model_name='species',
            name='size_max_record',
            field=models.FloatField(blank=True, null=True, validators=[home.models.validate_negative]),
        ),
    ]
